# Preliminary List of Journal Articles Week 02
 Week 02

| Title                                                                 | Author(s)              | Publication Year | Summary                                                                                     | Link                |
|-----------------------------------------------------------------------|------------------------|------------------|---------------------------------------------------------------------------------------------|---------------------|
| Blockchain Distributed Ledger Technology: An Introduction and Focus on Smart Contracts |             Marc Hamilton           | 2020             | Explores the fundamentals of blockchain technology with an emphasis on smart contracts and their applications in various industries. | [https://sci-hub.se/10.1002/jcaf.22421](#)           |
| Finance Infrastructure Through Blockchain-Based Tokenization           |    Junghoon Woo, Alastair Caithness, R. Edward Minchin, Peter Adriaens, Zheng Lu, Yifeng Tian                    | 2020             | Discusses how blockchain can be used to tokenize financial assets, improving the efficiency and transparency of financial markets. | [https://www.researchgate.net/publication/344891648_Finance_infrastructure_through_blockchain-based_tokenization](#)           |
| Decentralized Finance: On Blockchain- and Smart Contract-Based Financial Markets |     Fabian Schär                   | 2020            | Analyzes the emergence of decentralized finance (DeFi) and its impact on traditional financial systems. | [https://www.researchgate.net/publication/340061422_Decentralized_Finance_On_Blockchain-_and_Smart_Contract-based_Financial_Markets?_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6ImxvZ2luIiwicGFnZSI6InNlYXJjaCIsInBvc2l0aW9uIjoicGFnZUhlYWRlciJ9fQ](#)           |
| Distributed Ledger Technology in Payments, Clearing and Settlement     |   Maria Baird, Timothy Brezinski, Kathy Wang                    | 2017             | Examines how distributed ledger technology can transform payment systems, clearing, and settlement processes in finance. | [https://www.researchgate.net/publication/311334858_Distributed_Ledger_Technology_in_Payments_Clearing_and_Settlement?_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6ImxvZ2luIiwicGFnZSI6InNlYXJjaCIsInBvc2l0aW9uIjoicGFnZUhlYWRlciJ9fQ](#)           |
| DeFi-ning DeFi: Challenges & Pathway                                   |     Lisa Eckey, Sebastian Faust, Sebastian Faust, Benjamin Schlosser | 2021             | Explores the challenges and potential solutions in the decentralized finance ecosystem.      | [https://arxiv.org/pdf/2101.05589](#) |
| Proof of Concept of Blockchain Integration in P2P Lending for Developing Countries |    Fatou Ndiaye,  Mbodji Gervais , Mendy Ahmath, Bamba Mbacke S. Ouya  | 2020  (from a book)            | Investigates the application of blockchain technology in peer-to-peer lending, especially in developing countries. | [https://sci-hub.se/10.1007/978-3-030-41593-8_5](#)           |
| Scaling Up Sustainable Investment Through Blockchain-Based Project Bonds |      Ulrich Volz                  | 2022             | Discusses how blockchain-based project bonds can support sustainable investments and enhance financial inclusion. | [https://www.researchgate.net/publication/353267204_Scaling_up_sustainable_investment_through_blockchain-based_project_bonds](#)           |
| An Architecture for Blockchain-Based Cloud Banking                     |  Thuat Do                      | 2021             | Proposes a blockchain-based framework for cloud banking that improves security and operational efficiency. | [https://www.researchgate.net/publication/353052256_An_Architecture_for_Blockchain-Based_Cloud_Banking](#)           |
| Blockchain-Based Implementation of Smart Contract and Risk Management for Interest Rate Swap |                     Hongyao Zhu   | 2020             | Explores the use of smart contracts for risk management in interest rate swap transactions. | [https://sci-hub.se/10.1007/978-981-15-3278-8_14](#)           |
| Blockchain Technology Design in Accounting: Game Changer to Tackle Fraud or Technological Fairy Tale? |                        | 2021             | Examines the potential of blockchain to revolutionize accounting practices and tackle fraud. | [Link](#)           |

Ronith Rashmikara 
UGC0524027 - SE05
